# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories

# Paths to exclude from secret scanning
# These files contain INTENTIONALLY PUBLIC OAuth credentials from the Gemini CLI project
# Source: https://github.com/gzzhongqi/geminicli2api
# Desktop OAuth apps require embedded client credentials (this is Google's design)

paths-ignore:
  # Backend Gemini config - contains public Gemini CLI OAuth credentials
  - "backend/app/gemini/config.py"
  
  # Chrome extension Gemini constants - contains same public OAuth credentials
  - "chrome-extension/src-v2/shared/constants/gemini-constants.js"
  
  # Any test files that might reference these credentials
  - "backend/scripts/**"
  - "**/test_*.py"
  - "**/*_test.py"

